chalk-lab/Mooncake.jl

.github/workflows/CI.yml
Project.toml
ext/TapedSpecialFunctionsExt.jl
src/Taped.jl
src/rrules/lapack.jl
src/rrules/low_level_maths.jl
test/rrules/distributions.jl
test/rrules/lapack.jl
test/rrules/low_level_maths.jl
test/rrules/special_functions.jl
test/runtests.jl

Doesn't do all of them (turns out to be a bit trickier than I expected), but many of them turned out to be fairly straightforward.

Support more distributions

---

.gitignore
bench/Project.toml
bench/README.md
bench/run_benchmarks.jl

Adds a tool for looking at the results of the benchmarking analysis, and adds a note to the benchmarking readme to handle it.
Also adds a couple of additional items to the `.gitignore`.

Produce performance histogram

---

src/rrules/blas.jl

Uncomment tests

---

src/interpreter/reverse_mode_ad.jl
src/test_utils.jl
test/front_matter.jl
test/integration_testing/diff_tests.jl
test/interpreter/reverse_mode_ad.jl

Only store tangents in the general stacks -- pullback stacks take care of the primals

Only use stacks for tangents

---

Project.toml
ext/TapirLogDensityProblemsADExt.jl
src/Tapir.jl
test/integration_testing/logdensityproblemsad_interop.jl

Finish off the interop with LogDensityProblemsAD

ADTypes Interop

---

Project.toml
src/interpreter/ir_normalisation.jl
src/rrules/new.jl
src/test_utils.jl
test/interpreter/ir_normalisation.jl

Support splatnew instructions

---

test/integration_testing/temporalgps.jl

More TemporalGPs tests

---

src/Tapir.jl

At present, there is only so much I can do on this, because I don't yet have docs which provide enough background to explain the terms I've used. Once the docs are written, this docstring will make sense.
While the snippet makes sense, I've ensured that it is a failing `jldoctest`, so that when docs are written, I will be prompted to further improve this docstring.

Document rrule

---

Project.toml
src/interpreter/s2s_reverse_mode_ad.jl

This was just wrong. This PR fixes it.

Fix safety message printing

---

.github/workflows/documentation.yml
Project.toml
docs/Project.toml
ext/TapirLogDensityProblemsADExt.jl
test/integration_testing/logdensityproblemsad_interop.jl

LogDensityProblemsAD Safemode

---

README.md

Disambiguate vs Tapir for parallelism

---

README.md

Tweak readme again

---

Project.toml
ext/TapirLogDensityProblemsADExt.jl
test/integration_testing/logdensityproblemsad_interop.jl
test/runtests.jl

LogDensityProblemsAD parent method

---

Project.toml
ext/TapirJETExt.jl
src/test_utils.jl

JET Dep Removal

---

Project.toml
README.md
docs/make.jl
docs/src/debugging_and_mwes.md
docs/src/known_limitations.md
docs/src/mathematical_interpretation.md
src/chain_rules_macro.jl
src/test_utils.jl
test/chain_rules_macro.jl
test/front_matter.jl
test/integration_testing/array.jl
test/integration_testing/cuda.jl
test/integration_testing/diff_tests.jl
test/integration_testing/distributions.jl
test/integration_testing/gp.jl
test/integration_testing/misc.jl
test/integration_testing/special_functions.jl
test/integration_testing/temporalgps.jl
test/integration_testing/turing.jl
test/interpreter/s2s_reverse_mode_ad.jl

@sunxd3 hopefully these docs will make it clear how to conveniently go about running code to isolate your errors. Could you let me know if they're clear to you? If so, I'll merge.

Debugging + MWE Docs

---

docs/src/algorithmic_differentiation.md
docs/src/index.md
docs/src/mathematical_interpretation.md

@wesselb kindly gave me some feedback on the docs that we currently have. This PR is going to incorporate some of his suggestions + fix some typos.

Docs Improvements

---

.github/workflows/CI.yml
README.md

We're not currently reporting code coverage, but we ought to be.

Report Coverage

---

docs/src/mathematical_interpretation.md

Fix Docs Typo

---

.github/workflows/CI.yml
bench/README.md
bench/run_benchmarks.jl

@yebai pointed out that the benchmarks give a somewhat pessimistic lens into Tapir.jl's performance. This PR will play around with some of the parameters of the benchmarks to see if a more balanced view can be obtained.

Improve Benchmark Selection

---

.github/workflows/CI.yml

Do not run inter-AD from fork

---

Project.toml
src/fwds_rvs_data.jl
src/interpreter/bbcode.jl
src/interpreter/s2s_reverse_mode_ad.jl
src/interpreter/zero_like_rdata.jl
src/rrules/foreigncall.jl
src/test_utils.jl
test/fwds_rvs_data.jl
test/integration_testing/distributions.jl
test/interpreter/zero_like_rdata.jl

In the course of working through the various issues associated to Tapir + Turing integration, I've found a bunch more problems.
The one involving `PiNode`s was particular tricky to debug, and I'm glad to have found it.

Various fixes and extensions

---

Project.toml
src/codual.jl
src/fwds_rvs_data.jl
src/interpreter/abstract_interpretation.jl
src/interpreter/s2s_reverse_mode_ad.jl
src/safe_mode.jl
src/stack.jl
src/tangents.jl
src/test_utils.jl

WIP: Code caching (with some restrictions)

---

Project.toml
README.md
docs/src/debug_mode.md
ext/MooncakeLogDensityProblemsADExt.jl
src/rrules/lapack.jl
test/integration_testing/logdensityproblemsad_interop.jl

Finish off various items relating to the interaction between this package, `ADTypes.jl`, `DifferentiationInterface.jl`, and `LogDensityProblemsAD.jl`. Additionally, tidy up the README, and uncomment some items in the docs.

Complete renaming process

---

docs/src/mathematical_interpretation.md

Improve Docs

---

docs/src/mathematical_interpretation.md

There was a mathematical error in the docs -- the mistake was a kind of mathematical gotcha, so I've expanded on this a little bit.

Fix mistake in docs

---

Project.toml

The compat helper PR which was just merged required a version bump of Mooncake in order for it to be available to users.

Bump patch to enable DynamicPPL version bump to take effect

---

Project.toml
src/interpreter/s2s_reverse_mode_ad.jl

Make use of new MistyClosure functionality

---

Project.toml
src/tangents.jl

Hi!
I was trying this package out and I ran into an issue with `Enum` support where it wanted me to define a `tangent_type` for my `Enum` type. I think this PR fixes it according to my local tests. I don't have tests in this PR because I was not sure where the best place is to add the tests. Please let me know where you prefer I add the tests.
Great package btw!

enum support

---

Project.toml
src/rrules/builtins.jl
src/test_resources.jl

Simple test case for PartialTypeVar

---

.github/workflows/CI.yml
Project.toml
README.md
src/interpreter/ir_utils.jl
src/rrules/memory.jl
src/rrules/misc.jl
src/rrules/tasks.jl
test/front_matter.jl
test/runtests.jl

This found quite a number of method ambiguities that someone would eventually have run into, std libs on which I didn't have compat bounds, and a case where I had type-pirated Core.Compiler. All in all, adding this check was quite fruitful.

Run Aqua Checks

---

Project.toml
src/interpreter/s2s_reverse_mode_ad.jl

More minor performance tweaks

---

Project.toml
src/rrules/array_legacy.jl
src/rrules/memory.jl
src/tangents.jl
test/rrules/memory.jl

I believe the code that I already have in this PR is enough to fix the problem. I now need to double check that this is the case in all situations that I'm aware of, and write an isolated regression test. This should then be good to go.

Fix array tangent gen functionality

---

Project.toml
bench/run_benchmarks.jl
src/debug_mode.jl
src/interpreter/s2s_reverse_mode_ad.jl
src/test_resources.jl
test/interpreter/s2s_reverse_mode_ad.jl

I realised while working on the diffeq integration that some debug mode functionality (specifically to do with varargs) was broken -- this was because I wasn't testing it thoroughly enough. This PR checks that debug mode works properly on all of the tests in the basic test suite.

Test + Fix Debug Mode

---

Project.toml
src/interpreter/s2s_reverse_mode_ad.jl
src/rrules/blas.jl
src/rrules/builtins.jl
src/stack.jl

#419 did too much at once. I'm mainly working on GPU stuff this afternoon, but I'm going to slowly try to remove as many generated functions as possible in this PR, but do it one-by-one.
edit: uncovered a flakey BLAS test. Now uses StableRNG more consistently, should avoid this problem.

Cautiously make things not generated

---

bench/run_benchmarks.jl

Emzyme now supports operations required by the `gp_lml`benchmark model!

Test whether `gp_lml` works with Enzyme

---

Project.toml
src/tangents.jl

Sadly, it looks like introducing an additional generated function resolves some quite important inference issues uncovered in [this issue](https://github.com/nsiccha/StanBlocks.jl/issues/1). This should not be merged yet, because I've not managed to find an MWE which replicates the problem, so we don't yet have a regression test.

StanBlocks Perf Fix

---

Project.toml
src/rrules/blas.jl

Addresses #452 -- I'll discuss this further in the issue.

Improve trmv performance

---

Project.toml
src/interpreter/abstract_interpretation.jl
test/interpreter/abstract_interpretation.jl

Resolves #238 . Keno's explanation in https://github.com/JuliaLang/julia/issues/55638 appears to be correct. In particular, there's a large loop cycle (kind of) that the compiler seems to think means that it can't do inference properly.
I figured out this solution while trying to figure out what on earth is causing #458 not to work properly. Sadly, this doesn't fix that problem, but it _does_ mean we'll be able to close an issue that we currently have labelled as upstream.
todo:
edit: I've explained my debugging process in https://github.com/compintell/Mooncake.jl/issues/238#issuecomment-2639423674 , as it was quite involved.

Resolve 238

---

README.md
docs/src/index.md

Moves most of the README to the docs. Also ensures that there's an example using DI in the docs so that it can't be missed. This addresses #192 .

Tidy Up README

---

docs/src/index.md

@andreasKroepelin does this look like it's resolved the link problem?

Docs Links

---

Project.toml
src/interface.jl

Docstrings

---

README.md
docs/Project.toml
docs/make.jl
docs/src/index.md
docs/src/tutorial.md

- Add a tutorial for computing gradients:
- Fix a few esthetic things in Markdown files
cc @kshyatt

Add tutorial doc page

---

Project.toml
ext/MooncakeAllocCheckExt.jl
ext/MooncakeJETExt.jl
src/test_utils.jl
test/codual.jl
test/fwds_rvs_data.jl

There are a few small things which could do with being tidied up. This PR does that.

Some House Keeping

---

Project.toml
src/interpreter/patch_for_319.jl

Closes #493 (tested locally)
Not sure if you'd like a test — it seemed a bit overkill to add a DynamicPPL one for this!

Fix CC.getindex call

---

.github/workflows/CI.yml
Project.toml
src/Mooncake.jl
src/rrules/random.jl
test/rrules/random.jl
test/runtests.jl

This will address https://github.com/TuringLang/NormalizingFlows.jl/pull/46#issuecomment-2695521445 , just needs a small amount of tidying up.

Fix up some RNG behaviour

---

Project.toml
src/rrules/random.jl

Just adds a couple of extra tests to the functionality added in #506  -- after merging the previous PR I felt a little bit nervous that there were no integration tests.

More rand tests

---

Project.toml
src/Mooncake.jl
src/interpreter/bbcode.jl
src/interpreter/ir_utils.jl
src/interpreter/s2s_reverse_mode_ad.jl
test/interpreter/bbcode.jl
test/interpreter/s2s_reverse_mode_ad.jl

For the sake of hygiene, put BBCode in its own module.
This requires a little bit of formatting / shuffling of code around, but CI needs to run to check that I've refactored everything correctly.

Put BBCode in module

---

Project.toml
src/config.jl

A message from @mhauru prompted me to re-read the docstring for `Mooncake.Config`. It was previously rather unhelpful, so I've added some additional information to it.

Improve Config docstring

---

Project.toml
src/interpreter/bbcode.jl

I was toying around with this over the weekend. Small improvement to the successor implementation.

Successor Implementation

---

Project.toml
src/interpreter/s2s_reverse_mode_ad.jl
src/test_utils.jl

I think there are a couple of small ways that codegen can be improved that are 5-10 line tweaks. I'm hoping we'll see improvements in compile times.

Refactor rule derivation slightly

---

test/ext/luxlib/luxlib.jl

Fix Luxlib test suite

---

.github/workflows/CI.yml
Project.toml
README.md
docs/src/developer_documentation/misc_internals_notes.md
docs/src/developer_documentation/reverse_mode_design.md
docs/src/index.md
ext/MooncakeFluxExt.jl
src/interface.jl
src/interpreter/patch_for_319.jl
src/interpreter/s2s_reverse_mode_ad.jl
src/rrules/blas.jl
src/rrules/builtins.jl
src/rrules/performance_patches.jl
src/tangents.jl
src/test_resources.jl
test/interpreter/abstract_interpretation.jl
test/utils.jl

Change compintell to chalk-lab.

---

Project.toml
src/interpreter/ir_utils.jl
src/interpreter/s2s_reverse_mode_ad.jl
src/rrules/avoiding_non_differentiable_code.jl
src/rrules/foreigncall.jl
src/test_utils.jl
test/ext/cuda/cuda.jl
test/ext/nnlib/nnlib.jl
test/integration_testing/array/array.jl
test/interface.jl
test/tangents.jl
test/test_utils.jl

format and JuliaFormatter Bump

---

Project.toml

Reverts chalk-lab/Mooncake.jl#568

Revert "Update Mooncake version"

---

.github/workflows/PRAssign.yml

Disable PRAssign.yml workflow for PRs from forked repos 

---

test/ext/cuda/cuda.jl

https://github.com/chalk-lab/Mooncake.jl/pull/434 introduced a few minor issues, which this PR fixes.

Minor fixes

---

src/fwds_rvs_data.jl
src/test_resources.jl
test/fwds_rvs_data.jl

Hopefully fixes #598 for the final time

feat: handle more complex unions with nothing

---

src/interface.jl

fix a typo in docs

---

Project.toml
src/Mooncake.jl
src/tangents.jl

Ref https://github.com/TuringLang/DynamicPPL.jl/pull/975#discussion_r2235727500

Add `requires_cache` API for optimizing tangent operations without circular reference tracking

---

README.md

Tweak README to reflect the new forward-mode

---

README.md

Simplify `AutoMooncake()` in README

---

test/integration_testing/diffeq/diffeq.jl

Fix formatting

---

src/fwds_rvs_data.jl

Fix https://github.com/chalk-lab/Mooncake.jl/issues/704. Alternative to https://github.com/chalk-lab/Mooncake.jl/pull/716

Update zero_rdata_from_type to check for concretetype

---

Project.toml
src/tangents.jl
test/tangents.jl

Specialise require_tangent_cache for Arrays + add test cases
