chalk-lab/Mooncake.jl

src/tangents.jl, src/test_utils.jl, test/integration_testing/distributions.jl
I think my previous stance was unjustified -- treating everything like a container by default should be safe, in the sense that it will not introduce silent failure.
It has the advantage of making it possible for testing to work completely automatically on many more types. Moreover, it prevents false-positives, where some bits of a type which probably ought not to be ignored are in fact ignored.
It has the disadvantage of exposing _all_ of the fields of types to testing, which is not what people want in all situations, and will present itself as false negative failures. For example, if a `Symmetric` matrix is returned, the correctness of AD w.r.t the entire parent matrix will be checked, not just w.r.t one of the triangles. This is often fine, but in other cases the value in the (strict) …
=> Make container-like testing the default

test/rrules/builtins.jl
Verify that `getindex` and `setindex` work correctly when provided with repeated indices. (It turns out that they're fine, but it's good to know)
=> Extra setindex and getindex tests

src/test_utils.jl, test/rrules/iddict.jl, test/runtests.jl, test/tangents.jl
This PR addresses a couple of things which yesterday's PR left open:
1. improves tangent testing infrastructure, in order to do a better job of detecting whether a tangent type has enough of the testing interface implemented on it to be able to use it in automated testing infrastructure, and
2. adds another test case for IdDict which I realised I had missed off.
The improved testing infrastructure actually found a subtle bug to do with `Core.SimpleVector`s, which is also fixed in this PR.
=> Testing Improvements

src/interpreter/ir_normalisation.jl, src/rrules/builtins.jl, src/rrules/misc.jl, src/stack.jl, src/test_utils.jl, test/interpreter/ir_normalisation.jl, test/rrules/misc.jl, test/runtests.jl
We weren't lifting `setfield!`, meaning that constant values for `name` were not getting propagated, and type-stability was being lost. This PR sorts that out.
=> Improve setfield performance

src/interpreter/reverse_mode_ad.jl, src/tangents.jl
`tangent_type` was sometimes not properly constant folding. It only depended on the type of its argument anyway, so it is fine to just make it a generated function.
=> Tidy up and improve tangent_type performance

src/interpreter/abstract_interpretation.jl, src/interpreter/contexts.jl, src/interpreter/interpreted_function.jl, src/interpreter/reverse_mode_ad.jl, src/rrules/builtins.jl, src/test_utils.jl, test/interpreter/abstract_interpretation.jl
Modifies `is_primitive` to always accept the type of a context, rather than an instance, when deciding whether something is primitive or not. This doesn't affect any aspects of how things are currently implemented because only static properties are used anywhere at the minute.
This is partly paying down some tech debt (I've felt that this is probably the right thing to do for a while), but it's also important for the sake of performance when handling dynamic dispatch (there are some situations in which it's useful to know whether or not something is a primitive in the body of a generated function, which means that is_primitive can only depend on the type of the context).
edit: increase in line count is due to a new docstring for `is_primitive`. Everything else is a 1-for-1 replacement.
=> Static is_primitive

src/interpreter/reverse_mode_ad.jl, test/interpreter/reverse_mode_ad.jl
I missed this old implementation detail -- it was correct, but probably not incredibly performant. It's doubtful that it's ever a bottleneck, but still, good to improve.
=> Replace `Vector` stack with `Stack` stack

src/interpreter/interpreted_function.jl, src/interpreter/reverse_mode_ad.jl, src/stack.jl, test/interpreter/reverse_mode_ad.jl, test/stack.jl
Replace all slots with stacks in an AD context. This is the first step in the road to having only tangents in stacks, and optimising away loads of stuff once that is the case.
=> Stacks Not Slots

src/interpreter/interpreted_function.jl, src/interpreter/reverse_mode_ad.jl, src/stack.jl, src/tangents.jl, src/test_utils.jl, test/front_matter.jl, test/interpreter/reverse_mode_ad.jl
This PR changes the way that AD is implemented to ensure that PhiNodes are straightforward to handle. The rationale for this is that I keep discovering more and more edge cases involving undefined values in PhiNodes that previous iterations of AD were sensitive to (these are not bugs -- they are just part of how phi nodes work in Julia, and the documentation could do with some improving).
The strategy adopted here is to choose a way of doing AD which simply leaves phi nodes alone -- that is, the forwards-pass of AD for phi nodes is simply to run the exact same phi nodes with different data.
Various other bits of AD have to change to accomodate this, but the dramatic reduction in complexity associated to phi nodes means that, overall, the complexity is lower in the sense that there is no …
=> Simplify PhiNodes

src/interpreter/reverse_mode_ad.jl, src/stack.jl, src/tangents.jl, src/test_utils.jl, test/front_matter.jl, test/interpreter/reverse_mode_ad.jl, test/stack.jl, test/tangents.jl
Currently there are a lot of tangent stacks floating around that don't need to exist because they provably contain `NoTangent` elements, so there's really nothing to do with them.
This PR first will tidy up some of the functionality associated with specifying the tangent types of stacks, then go on to replace the usual stacks with a zero-overhead data structure to handle `NoTangent`s. This will improve performance by reducing the work that must be done at instructions associated to non-differentiable outputs, and at call sites with some non-differentiable arguments.
This PR will need to be followed up by another PR which makes more things have a `NoTangent` tangent type, or which allows more than one thing to represent the non-presence of a tangent (e.g. a maybe any singleton type should …
=> Optimise for NoTangent

src/interpreter/reverse_mode_ad.jl, src/test_utils.jl
Some dynamic information was used in a context that ought to have been purely static. This doesn't generally cause problems in my tests, but is absolutely 100% incorrect. This PR fixes this. Will probably knock performance in a number of cases because more dynamic dispatch will be used, but that's okay.
=> Dynamic Info Bug

src/interpreter/reverse_mode_ad.jl, src/test_utils.jl
If a rule has already been derived, don't re-derived it, just look it up from a cache of rules.
=> Cache Rules in AbstractInterpreter

ext/TapedSpecialFunctionsExt.jl, src/Taped.jl, src/chain_rules_macro.jl, test/chain_rules_macro.jl, test/front_matter.jl, test/integration_testing/special_functions.jl, test/runtests.jl
Adds a macro to make creating `rrule!!`s from `rrule`s straightforward. Use it to include a few more SpecialFunctions rules.
=> ChainRules Macro

Project.toml
It will be helpful to have a version of the package registered in order to get it working with the various AD interface packages, so I'm setting the version to pre-1.0 so that we can get going with that.
=> Set version

Project.toml, src/Tapir.jl
#105 points out that there appear to be redundant deps. This PR will remove them if it is in fact the case that they are unused.
=> Remove redundant deps

Project.toml, src/test_utils.jl
There is presently quite a bit of code-duplication in the tangent tests. Given that I'm about to refactor this interface, it makes sense to tidy it up to make refactoring as painless as possible.
=> Refactor tangent testing utils

Project.toml, src/interface.jl, test/interface.jl
As pointed out to me on slack, value_and_pullback / value_and_gradient currently return the wrong thing (they return the rdata rather than tangents).
=> Fix up interface

Project.toml, src/interface.jl, test/interface.jl
Adds some static checks to the `__value_and_pullback!!` interface to prevent accidentally calling a DerivedRule with incorrect arguments.
=> More safety checks for interface

Project.toml, src/rrules/builtins.jl, test/rrules/builtins.jl
This PR targets (what I see as) the central issue in https://github.com/withbayes/Tapir.jl/issues/114 -- `bitcast` drops important gradient information in the implementation of `Base.FastMath.exp_fast`. So solve this, I'm outlawing differentiation through `bitcast` when someone tries to cast _into_ a differentiable primitive type (`IEEEFloat`).
The second phase of this PR is to add rules for all of the functions in `Base.FastMaths`. ChainRules has rules for these, and I'd rather not copy + paste the code, so I _suspect_ that I'm going to have to add a dependency on ChainRules.
=> Tackle bitcast and fastmath

Project.toml, src/interface.jl, test/interface.jl
=> Error handling for self-referential types

Project.toml, src/interface.jl, test/interface.jl
I wasn't checking that safe mode can be used with `value_and_pullback!!` etc. Fortunately, DifferentiationInterface's CI caught the problem. This PR fixes the problem, and ensures that tests are run in safe mode.
=> Verify Safe Rule

Project.toml, src/interpreter/bbcode.jl, test/interpreter/bbcode.jl
The `Core.Compiler.CFG` object that `IRCode`s make use of ought to be trivial to compute from a `BBCode`. I'm trying this out to see if it actually is. It's quite helpful to have quick access to it, because there are some algorithms in `Core.Compiler` which do stuff with the CFG, e.g. compute the domtree.
=> Compute CFG

Project.toml, src/codual.jl, src/interpreter/ir_utils.jl, src/stack.jl, src/tangents.jl, test/codual.jl, test/interpreter/ir_utils.jl, test/stack.jl
A moderate amount of un-used code has accrued throughout the codebase. This PR is going to go through and remove as much stuff as possible.
=> Housekeeping

Project.toml, ext/TapirCUDAExt.jl, src/fwds_rvs_data.jl, src/interpreter/abstract_interpretation.jl, src/interpreter/ir_normalisation.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/builtins.jl, src/rrules/iddict.jl, src/safe_mode.jl, src/tangents.jl, src/test_utils.jl, src/utils.jl, test/front_matter.jl, test/fwds_rvs_data.jl, test/integration_testing/turing.jl, test/interpreter/s2s_reverse_mode_ad.jl, test/safe_mode.jl, test/tangents.jl
I'm slowly working through a few problems that arise when type instabilities appear for large SimpleVarInfo models. Many were previously resolved by dealing with splatnew and _apply_iterate. I'll remove the WIP label when this is ready to be merged.
I'm trying to be careful while going through to figure out what the underlying problem is for each failure, isolate it, unit test it, and fix it, as these won't be Turing-specific.
update: this now just about works, but something else has broken. Said break hasn't been picked up as it ought to be by the safe mode checks (it errors later than it ought to), so I'm going to spend tomorrow improving that quality of the checks performed as part of safe mode.
=> More fixes for SimpleVarInfo for large models

Project.toml, ext/TapirLogDensityProblemsADExt.jl, test/integration_testing/gp.jl
Prints the following when running in safe mode in LogDensityProblemsAD via AutoTapir:
```julia
julia> @time sample(Xoshiro(123456), m_post, NUTS(; adtype=AutoTapir(safe_mode=true)), 1_000)
[ Info: Running Tapir in safe mode. Disable for best performance. Do this by using AutoTapir(safe_mode=false).
```
This is in the context of me running a Turing.jl model.
Also fixes some integration tests for GPs which weren't previously running properly.
=> Safe mode warning with LogDensityProblemsAD and GP testing

.github/workflows/CI.yml, src/rrules/builtins.jl
The performance ratios will differ a lot depending on where you run them. Add a note to tell people to be cautious.
edit: additionally, in a previous PR, I had accidentally deactivated a large number of tests that really ought not to have been deactivated. Revert that.
=> Add note of caution to performance ratios and uncomment tests

Project.toml, src/codual.jl, src/fwds_rvs_data.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/builtins.jl, src/rrules/iddict.jl, src/rrules/misc.jl, src/tangents.jl, src/test_utils.jl, test/front_matter.jl, test/fwds_rvs_data.jl, test/interpreter/s2s_reverse_mode_ad.jl
=> Abstract Fields in Arguments

Project.toml, src/Tapir.jl, src/fwds_rvs_data.jl, src/rrules/misc.jl, src/rrules/tasks.jl, src/tangents.jl, test/rrules/tasks.jl, test/runtests.jl
This PR will resolve #182 . It adds _incredibly_ narrow support for getfield and setfield on tasks. You should not expect to actually be able to work properly with tasks as a consequence of this PR, just that they shouldn't get in the way when used as part of random number generation.
=> Make getfield on tasks work

Project.toml, ext/TapirJETExt.jl, src/test_utils.jl
Plan:
1. replace calls to `JET.report_opt` and `JET.test_opt` with calls to placeholder functions which always errors, and suggests loading JET
2. create extension for Tapir + JET which defines method of this placeholder function which actually does the right thing.
=> Make JET a test-only dep

Project.toml, src/rrules/builtins.jl, src/tangents.jl
Resolves a couple of small problems needed to make #202 run.
=> Fix Assorted Problems

Project.toml, src/fwds_rvs_data.jl, src/interpreter/ir_normalisation.jl, src/interpreter/ir_utils.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/tangents.jl, src/test_utils.jl, src/utils.jl, test/fwds_rvs_data.jl
This PR largely resolves #206 -- in particular it makes `invoke(f, TT, args...)` work nicely when `f` and `TT` can be resolved statically.
=> invoke attempt 2

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/blas.jl, src/utils.jl
At the minute, it is quite common for Tapir to error in a way that is quite uninformative if inference fails. This PR attempts to prevent this from happening by running the forwards-pass of AD if the return type isn't what we expect, rather than letting everything fall over without saying _why_.
=> Attempt to get better errors

Project.toml, src/rrules/builtins.jl, test/rrules/builtins.jl
=> Improve Intrinsics

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/blas.jl
Adds a missing rule for `BLAS.symm!`. I believe that this is the last missing Level 3 BLAS rule that we were missing!
=> symm rrule implementation

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/builtins.jl
- Adds rule for `Core.Intrinsics.fptrunc`.
- Includes the signature in `LazyDerivedRule` again -- this is a very useful thing to have in the stack trace when trying to isolate problems.
=> fptrunc and more debugging info

Project.toml, src/codual.jl, src/rrules/builtins.jl, test/codual.jl
=> Handle undefined type parameters in fcodual_type and implement rule for fpext

.github/workflows/CI.yml, Project.toml, src/interface.jl, src/rrules/low_level_maths.jl, test/interface.jl
We still can't properly test `Float32`, so do not treat this PR as saying that Tapir.jl is now safe to use with `Float32`. Rather, the purpose is to unblock `Float32` usage in some situations that I'm pretty sure that it's safe to do so.
=> Some very basic Float32 support

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/blas.jl, src/rrules/foreigncall.jl
This PR just adds `GC.@preserve` statements in bunch of places, and ensures that only one thread is doing inference at a time -- this seems to resolve any thread safety issues on my end. Annoyingly, it's not at all clear to me how best to write unit tests for this behaviour, so it's not tested.
=> GC Preservation and Thread Safety

Project.toml, docs/src/known_limitations.md, src/interpreter/s2s_reverse_mode_ad.jl, src/test_utils.jl, test/interpreter/s2s_reverse_mode_ad.jl
We say in a couple of places that non-constant `GlobalRef`s, or constant `GlobalRef`s containing mutable data, cannot be used. Unfortunately, this hasn't actually been enforced anywhere. This PR enforces it more carefully, and provides reasonable error messages that explain what has happened when someone attempts to do this.
edit: sadly, it's not possible yet to properly prevent all of the things that could go wrong. I'm going to add a note to the docs explaining what you ought not to do with globals.
=> Disable More Unsafe GlobalRef Uses

Project.toml, src/codual.jl, src/fwds_rvs_data.jl, src/rrules/foreigncall.jl, test/fwds_rvs_data.jl
Previously, the `rrule!!` for `hash` was rather conservative in the cases that it attempted to cover. Any reasonable implementation of `hash` is going not going to be differentiable, since it returns an integer, so I've just made it so that _all_ methods of `hash` have `NoPullback` returned.
This is necessary in some cases to avoid ccalls, but will be a good performance optimisation in many cases.
=> NoPullback for hash

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl
I currently run multiple optimisation passes, because at some point in the past this was necessary in order to get everything to infer properly. I'm running the test suite to try and figure out if this is still true, or if it's in fact gone away, and we can get away with optimising just once.
If it is, I'll merge this and tag a release, because optimising twice feels 1) silly, and 2) sometimes causes problems during inlining.
=> Remove multiple optimisation passes

Project.toml, docs/src/debugging_and_mwes.md, docs/src/known_limitations.md, ext/TapirLogDensityProblemsADExt.jl, src/Tapir.jl, src/interpreter/abstract_interpretation.jl, test/chain_rules_macro.jl, test/interpreter/s2s_reverse_mode_ad.jl
I hadn't propagated the way that rule caching happens in a previous PR to `ADgradient`, which meant we were seeing time-outs in the Turing.jl CI. This fixes that.
Sadly, I don't know how to write unit tests for this, so it all feels a little bit fragile. If I think of anything at a later date, I'll add it in to Tapir.jl, but for now I would like to get this merged asap so that Turing.jl's tests pass again.
edit: @yebai this should resolve the problem that we discussed on slack.
=> Fix Caching in ADgradient

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/interpreter/s2s_reverse_mode_ad.jl
I had introduced some fairly conservative world age checks in a previous PR, the purpose of which was to err on the side of caution, and insist that you only attempt to derive a rule based on the current world age. Unfortunately, this doesn't interact well with BenchmarkTools, because it typically progresses the world age, and you have to have constructed a rule by the time that a call to `@benchmark` is made.
This PR doesn't relax the world age assumption, but does make a point of updating the interpreter more regularly, to prevent it from getting behind.
=> Fix World Age Problems

Project.toml, src/rrules/low_level_maths.jl, test/front_matter.jl, test/rrules/low_level_maths.jl
There are some low-level functions which ought not to have rules, because there's perfectly good low-level functionality which handles them.
=> Some small improvements to low-level rules

Project.toml, src/interface.jl, test/interface.jl
=> Handle varargs correctly in value_and_pullback!! and value_and_gradient!!

Project.toml, src/interpreter/zero_like_rdata.jl, test/interpreter/zero_like_rdata.jl
I'm opening this as an easy way to run the entire test suite to see what fails when I remove this. Do not merge.
update: this actually can be merged -- it looks like these method were redundant. They don't make any sense anyway because a `TypeVar` is not a type, so they really ought not to exist. I'll update, bump the patch, and merge when CI passes.
=> Remove Method of zero_like_rdata_from_type

Project.toml, src/fwds_rvs_data.jl, test/fwds_rvs_data.jl
=> Handle `Union`s / `UnionAll`s of `Tuple`s in zero_rdata

Project.toml, src/rrules/foreigncall.jl
The foreigncall rrule test suite reliably segfaults due to user-error (I failed to properly preserve the data underlying some pointers I'm using in some tests).
=> Fix foreigncall test suite

.github/workflows/CI.yml, Project.toml, src/rrules/blas.jl
Addresses #289 . Sadly, I think I need to add an 32 bit runner to ensure that this works correctly.
edit: a single x86 run has been added. Once CI has passed, I'll check that CI on the x86 runner does actually fail without the change made in this PR, before re-running CI and merging.
=> Fix BLAS / LAPACK calls on x86

Project.toml, src/fwds_rvs_data.jl, test/fwds_rvs_data.jl
I believe that this resolves #282 .
=> Fix TypeVar Bug

Project.toml, src/test_resources.jl
As pointed out by @sunxd3 a while ago, the `TypeStableStruct` inner constructors are nonsense. This PR fixes them, and resolves #221 . I'll bump the patch version + merge once #299 has been merged.
=> Fix TypeStableStruct constructors

docs/make.jl, docs/src/running_tests_locally.md
Addresses #268 . @sunxd3 would you mind taking a quick look at this and letting me know if it is clear? I feel like you have most experience developing Mooncake after me, so you are likely best positioned to judge this.
=> Add Dev Workflow Docs

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/integration_testing/distributions.jl, test/interpreter/s2s_reverse_mode_ad.jl
It appears to be the case that, as of 1.11, `PiNode`s are encountered in the wild which can contain constants. While I don't fully understand why these are necessary, handling them seems important to get e.g. Distributions.jl tests with certain kinds of truncations to work properly.
I believe that this will resolve #303 .
=> PiNodes with GlobalRefs and Constants

Project.toml, src/interpreter/abstract_interpretation.jl, test/front_matter.jl, test/interpreter/abstract_interpretation.jl
Should resolve the new problem in #282 .
Occasionally, the inference result associated to an SSA is `Core.Compiler.PartialTypeVar`. This means that inference has successfully determined that the SSA will be a `TypeVar`. More than that, it has figured out some of the runtime information about the SSA, in a similar sense (I believe) to the way that `Core.Compiler.PartialStruct` knows some runtime information about a given `struct`. I've asked on slack for a MWE of a function in which this is the result of inference. I'll wait a few hours, but will merge this with the current unit test if I nothing appears.
edit: many of the people who would know about this are based in the US. I'll get this merged asap, and make a new PR if an MWE becomes available.
=> Correctly handle PartialTypeVars in inference

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl
Resolves a problem that @sunxd3 encountered when generating a large unrolled IR.
I've yet to produce a MWR, but will attempt to do so before merging. @sunxd3 could you run this branch on your problem to confirm that it indeed resolves the issue? (it does on my machine, I'm just keen to ensure that it does also on other machines)
edit: I do not understand _why_ this resolves the problem. Presumably there is some limitation of `vcat(x...)` that tends not to be hit.
=> Prevent Stack Overflow

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/interpreter/s2s_reverse_mode_ad.jl
The rather cryptic error message shown in #310 is the result of a bug. This PR improves this error message by giving it is own type, and tests that it throws correctly when expected to do so.
=> Fix Error Message

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/test_resources.jl
Functions which have signatures like `foo(::Type{P}) where {P}` don't play nicely with instances of `P` which have unbound type variables. If `foo` happens to be generated, the error does not look like what you would expect to get.
This PR resolves this problem by ensuring that that code path never gets hit for `__make_ref`, as this was causing problems in AdvancedVI. I've added a test which makes use of low-level machinery, to hopefully ensure that this doesn't become a problem again.
=> Fix problem with unbound type parameters

Project.toml, ext/MooncakeLogDensityProblemsADExt.jl, src/debug_mode.jl, src/interpreter/s2s_reverse_mode_ad.jl, test/debug_mode.jl, test/ext/logdensityproblemsad.jl
Improves debug_mode by additionally checking whether the primals of the arguments passed to a rule as the ones that the rule expects. Not doing this seems to cause segfaults occasionally.
=> Improve debug mode and permit all IEEEFloats in ADgradient

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/test_resources.jl, src/tools_for_rules.jl, test/ext/special_functions/special_functions.jl, test/tools_for_rules.jl
Per #330 there are some limitations associated to SpecialFunctions.jl left over from yesterday's work. This PR will fix them, and close this issue. As part of this, it will also resolve #329 , as this is causing some derived rules for SpecialFunctions to allocate when they ought not to.
=> Fix Remaining SpecialFunctions Limitations

.github/workflows/CI.yml, test/integration_testing/logexpfunctions/Project.toml, test/integration_testing/logexpfunctions/logexpfunctions.jl, test/runtests.jl
I realised that we're not currently testing against LogExpFunctions, which feels like an oversight. Happily, it doesn't look like we need any of the rules defined in that package in order to get correctness, and to ensure that things which ought not allocate to not in fact allocate.
=> Add LogExpFunctions integration testing

Project.toml, src/interpreter/ir_utils.jl, src/interpreter/s2s_reverse_mode_ad.jl, test/interpreter/s2s_reverse_mode_ad.jl
Addresses the remainder of #326 .
The error message associated to the `UpsilonNode` problem as been improved. With the new error messages, you would have seen something like:
```julia
caused by: Mooncake.UnhandledLanguageFeatureException("Encountered UpsilonNode: ϒ (%2). These are generated as part of some try / catch / finally blocks. At the present time, Mooncake.jl cannot differentiate through these, so they must be avoided. Strategies for resolving this error include re-writing code such that it avoids generating any UpsilonNodes, or writing a rule to differentiate the code by hand. If you are in any doubt as to what to do, please request assistance by opening an issue at github.com/compintell/Mooncake.jl.")
Stacktrace:
[1] unhandled_feature(msg::String)
@ Mooncake …
```
=> Improve error messages generated by the Mooncake compiler

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/integration_testing/misc_abstract_array.jl
While working on #320 I've encountered a couple of small improvements that I can make.
=> Some Minor Performance Tweaks

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/interpreter/s2s_reverse_mode_ad.jl
While looking at some performance profiles over the weekend, I discovered that there was some stuff being put in shared memory that ought to just have been interpolated directly into the generated code. It is unclear whether this will have a massive performance implication anywhere, but it will certainly tidy up the shared data a bit.
=> Remove some literals from shared data

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/test_resources.jl, test/interpreter/s2s_reverse_mode_ad.jl
Reverts a change that was made in https://github.com/compintell/Mooncake.jl/pull/339 . In that PR, I changed the implementation of `rule_type` in such a way that it didn't agree with what type inference produced when I actually derived a rule. This causes some problems, so I've reverted it.
A regression test has been added to catch the offending case, found by @penelopeysm in #345 . I've checked that this fixes the problem locally.
=> Fix Rule Type

.github/workflows/CI.yml, test/integration_testing/bijectors/Project.toml, test/integration_testing/bijectors/bijectors.jl, test/runtests.jl
Copied over from https://github.com/EnzymeAD/Enzyme.jl/pull/2037.
Closes #348
=> Add Bijectors integration tests

Project.toml, src/test_utils.jl
@mhauru pointed out to me that the `test_rule` docstring didn't properly explain the various kwargs. This rectifies the situation.
=> Improve test_rule docs

Project.toml, ext/MooncakeCUDAExt.jl, src/rrules/array_legacy.jl, src/rrules/iddict.jl, src/rrules/memory.jl, src/rrules/tasks.jl, src/tangents.jl, src/test_resources.jl, src/test_utils.jl, test/ext/dynamic_ppl/dynamic_ppl.jl, test/integration_testing/bijectors/bijectors.jl, test/integration_testing/diff_tests.jl, test/integration_testing/gp/gp.jl, test/integration_testing/temporalgps/temporalgps.jl, test/integration_testing/turing/turing.jl, test/tangents.jl
If you attempt to test Mooncake on functions / arguments for which the default constructor is not available (i.e. someone has defined a custom inner constructor and it prevents you from just writing `MyType{T, V}(args...)` to construct an instance of `MyType{T, V}`), then the default functionality won't work. This PR makes it possible to opt-in to functionality which bypasses the constructors, and instead just calls the `:new` instruction on the type of interest. This is, in general, not a safe thing to do (in general, people write custom inner constructors for a reason), but often it's completely fine to do.
As a consequence of enabling this functionality, the tests of Turing.jl and KernelFunctions.jl / AbstractGPs.jl now actually test the numerical correctness of their results (happily, …
=> Permit opting in to unsafe perturbations

Project.toml, bench/run_benchmarks.jl, docs/src/running_tests_locally.md, src/Mooncake.jl, src/rrules/function_wrappers.jl, src/test_utils.jl, src/tools_for_rules.jl, test/rrules/function_wrappers.jl, test/tools_for_rules.jl
There are a few small things which Mooncake needs to have before the PR I want to make to DiffEqBase will work at all, so this adds this functionality. Once it's tagged + released, I'll be able to open a PR against SciMLSensitivity.
=> Final Tweaks before DiffEqBase PR

Project.toml, src/codual.jl, src/interpreter/bbcode.jl, src/interpreter/ir_utils.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/test_resources.jl
I was taking a quick look through our coverage report. While there are a few things which will require some actual work to improve, there are a number of things which are completely redundant. Presumably at some point they were used for something, but now it appears that they are not.
=> Remove some obviously redundant code

Project.toml, src/fwds_rvs_data.jl, src/interface.jl, src/tangents.jl, test/interface.jl
This PR
1. makes a function generated, because type inference sometimes falls over for it in some situations which matter, and
2. moves the pre-allocation functionality in-house. It's largely a generalisation of stuff that's already been written in DI.jl, but having it here lets us test it thoroughly here, and then get DI.jl to just use it. This increases the level of confidence that it's possible for me to have that when a user uses DI.jl, they're getting the best possible level of performance.
Todo:
=> Perf and Pre-Allocation

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, test/interpreter/s2s_reverse_mode_ad.jl
Sometimes, we're unable to correctly predict the output type of the forwards-pass of a rule. As far as I can tell, this only happens in edge-cases involving type instability, where performance is bad anyway. Importantly, it never happens when the primal is completely type-stable because the type is very predictable in those cases.
Currently we generate a warning when this happens because, historically, I only expected this to happen when something had gone badly wrong with AD. Since this isn't really the case anymore, I'm inclined to not produce the warning.
=> Do not warn on failed return type guessing

Project.toml, src/rrules/blas.jl
#407 improved both gemv performance, and the scope of the implementation of the rule for `BLAS.gemm!`. I believe it made the rule for the underlying foreigncall redundant. This PR is to check that this belief is true, and to remove it if so.
=> Remove Redundant gemm Code

Project.toml, ext/MooncakeLuxLibSLEEFPiratesExtension.jl
In https://github.com/compintell/Mooncake.jl/pull/377 we introduced a hack which ensured that code was loaded in roughly the correct order when extensions depended upon other extensions. Happily this ceased to be necessary in 1.11.2, so this PR
1. removes the hacky code
2. modifies the Julia compat bound to ensure that people still running 1.11.0 or 1.11.1 do not see this problem.
=> Remove hack and insist on Julia version upgrade

bench/run_benchmarks.jl
I had deactivated the Enzyme results in the table which gets pasted into each PR when 1.11 was released, because there were some compat issues with Turing.jl. These seem to be resolved, so I'm re-enabling. Additionally, I'm now comparing with `ReverseWithValue`, rather than `Reverse`, because this is a like-for-like comparison with what the other frameworks are doing.
=> Reactivate enzyme comparison + use WithValue

Project.toml, src/rrules/blas.jl, src/rrules/lapack.jl
This PR introduces a more generic mechanism for handling different array types with BLAS, and resolves the immediate problem associated with #423 .
=> Reshaped Arrays + BLAS + LAPACK

Project.toml, src/rrules/blas.jl, test/rrules/blas.jl
Extends #424 slightly with an improved error message. Hopefully it'll mean that if someone encounters a related error in future, it will be really very straightforward to fix the problem quickly.
=> Improved Error Message

docs/src/understanding_mooncake/algorithmic_differentiation.md
This PR fixes a typo in an example from the documentation. Instead of a large PR with multiple documentation typo fixes, I will submit separate PRs in the future if I see typos.
=> corrected matrix multiplication example

Project.toml, src/interpreter/abstract_interpretation.jl, src/interpreter/ir_normalisation.jl, src/interpreter/ir_utils.jl, src/interpreter/s2s_reverse_mode_ad.jl, test/front_matter.jl, test/interpreter/abstract_interpretation.jl
In my adventures to make everything in #426 work properly, I discovered that the compiler has a function `Core.Compiler.widenconst`, which is almost exactly what my `Mooncake._type` function does.
This PR looks at replacing Mooncake's `_type` functionality` with `widenconst`, as this is obviously a better thing to do.
There's a slight discrepancy between how `CC.widentconst` and `Mooncake._type` handle `CC.Conditional`s, but I suspect my version is just wrong.
In this PR I've replaced the various methods of `_type` with a single method that just defers the call to `CC.widenconst`. This was the quickest way to make a PR and see if it works. If CI passes, I'll remove the `_type` function entirely, and replace all calls to `_type` with `widenconst` before merging.
=> Replace _type with widenconst

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/utils.jl, test/interpreter/s2s_reverse_mode_ad.jl, test/utils.jl
A really annoying class of errors is handled here: https://github.com/compintell/Mooncake.jl/blob/8c478a88bbd89d12507441314f21fb193e4eceef/src/interpreter/s2s_reverse_mode_ad.jl#L1726
This error occurs because we have to guess what type inference is going infer the return for the forwards-pass IR to be, based on the primal IR (its argument types and return type). We are able to correctly guess this type the vast majority of the time on correctly derived code -- we only occasionally runs into problems when inference does quite special things for e.g. small unions of `Tuple`s. However, this is a loosing battle -- see the docstring for the new `opaque_closure` function for more details.
The bigger problem is this: when something goes wrong when deriving a rule we often see this error, rather …
=> Eliminate Rule Type Mismatch Errors Forever

Project.toml, src/interface.jl, src/interpreter/s2s_reverse_mode_ad.jl
Reduces the amount of clutter in a couple of types, this de-cluttering stack traces a bit.
=> Tidy Up Types

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl
Moves preparation of some `Base.RefValue`s which are used on the reverse-pass to compile time.
The reason for doing this is to
1. ensure performance robustness -- the new line of code is literally just a `:new` instruction, with all other prep having been done beforehand. There is very little that can go wrong here. Conversely, we previously had calls to `Mooncake.__make_ref` inserted into the IR, which itself called `Mooncake.zero_like_rdata_type` and `Mooncake.zero_like_rdata_from_type`. While there are _meant_ to always be performant, it's hard to ensure this 100% of the time. Now, these functions get called at compile-time, and insert their results directly into the IR. Consequently, even if the performance of these functions is poor, it won't show up at runtime.
2. make errors happen …
=> Compile Time Ref Prep

Project.toml, src/interpreter/contexts.jl, src/tools_for_rules.jl, test/interpreter/contexts.jl, test/tools_for_rules.jl
Addresses #440 + previously undiscovered issues around escaping for `@zero_adjoint` and `@mooncake_overlay`. Regression prevented by not importing `Mooncake` into the module which defines the tests for these macros (see comment in tests).
Before merging, I'm going to fix up the hygiene of a couple of other macros.
=> Fix Escaping

Project.toml, src/fwds_rvs_data.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/interpreter/zero_like_rdata.jl, src/utils.jl, test/ext/special_functions/special_functions.jl, test/interpreter/s2s_reverse_mode_ad.jl
This PR contains some work to ensure that various `Ref`s inserted into the reverse-pass IR always get SROA'd away reliably. This is a PR in the same vein as https://github.com/compintell/Mooncake.jl/pull/430 and https://github.com/compintell/Mooncake.jl/pull/438 -- change how things are implemented to ensure that we're completely insensitive to what type inference / constant prop happens to let us do. The pay off for this kind of work is not receiving hard-to-debug issues in the future / users seeing poor performance, not telling us about it, and giving up on Mooncake entirely.
In short, a variety of Julia functions are inserted into the reverse pass IR at them minute, whose calls _must_ get inlined away if SROA is to successfully remove the `Ref`s. There are various reasons that Julia …
=> Performance Robustness in Reverse Pass

docs/make.jl, docs/src/developer_documentation/misc_internals_notes.md
Adds a note on the implementation of `tangent_type` and related functions. No version bump required because it's all in the docs.
=> Add note on tangent type implementation

Project.toml, src/interpreter/s2s_reverse_mode_ad.jl, src/test_resources.jl
Fixes #450 -- this was a systematic problem in the way that we were counting the number of arguments provided to a call site when the call involved a `Vararg`. More explanation to follow later today. The seemingly substantial changes to the plumbing of rule construction are really just needed to change the way in which the number of arguments which are passed to a function are counted (looking at the actual number, rather than looking at the signature, which sometimes doesn't contain sufficient information, as it turns out).
todo:
edit: what was going wrong?
If you have a function of the form
```julia
f(x, y...) = ...
```
you'll see non-splatted calls to it appear in `IRCode` as `f(a, b, c, d)`. For book-keeping-related reasons, we need to know how many elements appear in `y` inside a …
=> Vargargs Bug

Project.toml, src/tangents.jl, test/tangents.jl
Just adds `NoTangent` tangent types for `Cstring` and `Cwstring`. I've confirmed locally that this ensures that @penelopeysm 's example in #484 successfully errors on the bug from #319 instead of asking you to define `tangent_type` for `Cstring`!
=> Cstring and Cwstring

Project.toml, ext/MooncakeCUDAExt.jl, src/fwds_rvs_data.jl, src/rrules/iddict.jl, src/rrules/memory.jl, src/rrules/twice_precision.jl, src/tangents.jl, src/test_utils.jl, test/front_matter.jl, test/fwds_rvs_data.jl
Some investigations in TemporalGPs.jl revealed a performance issue with `Mooncake.can_produce_zero_rdata_from_type`. As with `tangent_type` and friends, the most reliable way to get this to have the correct behaviour is to use `Base.@assume_effects :foldable`.
Since this functionality is required across a few functions, I've
1. renamed `@tt_effects` to the much more readable `@foldable`,
2. declared all methods of `Mooncake.can_produce_zero_rdata_from_type` to be `@foldable`, and
3. added regression tests to `Mooncake.can_produce_zero_rdata_from_type`.
=> Fix can_produce_zero_rdata_from_type performance

Project.toml, ext/MooncakeCUDAExt.jl, src/fwds_rvs_data.jl, src/rrules/function_wrappers.jl, src/rrules/iddict.jl, src/rrules/memory.jl, src/rrules/twice_precision.jl, src/test_utils.jl
The binary method of `tangent_type` could sometimes fail to constant-fold properly for tricky examples, in the same way that the unary method previously could.
The solution is to
1. use Mooncake's new `@foldable` macro to just declare that it's foldable, and
2. insert a `@test is_foldable(...)` in the test suite for `test_fwds_rvs_data` to ensure that it always holds.
=> Performance of binary method of tangent_type

Project.toml, ext/MooncakeCUDAExt.jl, src/rrules/function_wrappers.jl, src/rrules/iddict.jl, src/rrules/memory.jl, src/rrules/tasks.jl, src/rrules/twice_precision.jl, src/tangents.jl, src/test_resources.jl, src/test_utils.jl
Inference / constant propagation in zero_tangent_internal will currently occasionally fall over, for all of the usual reasons. It's necessary to use a generated function to iterate over the fields of the type.
While here, I'm updating the requirements imposed on `zero_tangent_internal`'s stackdict -- in particular insisting that it's of the same type as that used for various other related functions (`set_to_zero!!` etc).
todo:
edit: just waiting for CI to pass, then I'll merge + release.
=> zero_tangent_internal performance

Project.toml, src/rrules/blas.jl
When I was skimming through @GiggleLiu 's PR, I realised I had forgotten to suggest that we move the code for `nrm2` to the block of code containing rules for the level 1 blas routines. Also, there was a redundant comment about testing on complex numbes that I missed during code review. So there's really no functional changes in this PR whatsoever -- it's all cosmetic.
=> Shuffle Code Around

Project.toml, src/stack.jl
After digging around a bit in #499 , it looks like most of the performance gains that weren't associated with a pathologically-unsafe use of `unsafe_store!` were associated to disabling bounds checking when popping elements from `Stack`s:
```julia
julia> using BenchmarkTools, Mooncake
julia> function push_stack(s::Mooncake.Stack{T}) where {T}
@inbounds for _ in 1:10_000_000
push!(s, T(false))
end
return nothing
end
push_stack (generic function with 1 method)
julia> function pop_stack(s::Mooncake.Stack{T}) where {T}
t = zero(T)
@inbounds for _ in 1:1_000
t = pop!(s)
end
return t
end
pop_stack (generic function with 1 method)
julia> @benchmark (push_stack($s); pop_stack($s)) # with bounds checking disabled
BenchmarkTools.Trial: 10000 samples with 10 evaluations per sample.
Range (min … …
```
=> Improve Stack Performance v2

bench/run_benchmarks.jl
I think it's possible that the variance we often see in benchmarks is because we're not properly GC-ing between benchmarks. This PR hopefully addresses this problem, although it's obviously rather hard to know whether this has worked from a single run.
=> GC between benchmarks

.github/workflows/CI.yml, Project.toml, src/rrules/array_legacy.jl, test/rrules/array_legacy.jl, test/runtests.jl
#513 highlights that #505 only addressed `Memory` / `MemoryRef`s, and therefore didn't address an equivalent issue on 1.10. This PR just fixes that.
It also ensures that we run the tests for the legacy rules. Concerningly, we were not previously doing so...
=> Fix unsafe_copyto on 1.10

Project.toml, src/rrules/random.jl
The constructor for MersenneTwister appears to have a `ccall` in it, meaning that we couldn't differentiate through its construction. This PR introduces a patch for it. It also adds tests to make sure that all of the standard random number generators can be correctly constructed.
=> Minor RNG Improvements

Project.toml, src/codual.jl, src/fwds_rvs_data.jl, src/interpreter/s2s_reverse_mode_ad.jl, src/rrules/builtins.jl, src/tangents.jl, test/fwds_rvs_data.jl, test/rrules/builtins.jl, test/tangents.jl
Adds an `rrule!!` for throw, which has the behaviour that it just throws the original exception. I might tweak this to add a little bit more context at a later date, because currently it's not currently quite as informative as it might be.
Addresses part of #534
=> Rule for throw

.github/workflows/CI.yml, .github/workflows/documentation.yml, docs/src/index.md, docs/src/known_limitations.md
=> unify known limitations into one page

Project.toml, src/rrules/blas.jl, test/rrules/blas.jl
Should fix #577.
I tried to implement  a test using the `hand_written_rrule!!_test_cases`, but that fails because Base.ReinterpretArray does not have a default constructor. The error messages suggested to try `unsafe_perturb` but it this does not seem to be accessible from the test case tuple.
=> Add arrayify for ReinterpretArray

docs/src/understanding_mooncake/rule_system.md, src/developer_tools.jl
fix a grammatical error and try to get the warning blocks to render nicely
=> Some minor doc updates

src/fwds_rvs_data.jl, src/tangents.jl, src/test_resources.jl, test/fwds_rvs_data.jl
This PR improved tests initially introduced by #599. 
Only the union of `Nothing` and `Base.IEEEFloat` is supported; these union types are also only supported for struct field annotation. Other use cases may fail.
=> Tweak a few tests for tangents

src/fwds_rvs_data.jl, src/test_utils.jl, test/fwds_rvs_data.jl
=> Minor refactoring of `Union{Nothing, Array{<:Base.IEEEFloat}, Base.IEEEFloat}` support 

Project.toml, src/interface.jl, test/interface.jl
Checking for `Ptr` types etc. can only be done if we primal check before running the forward pass for the derived rules/generate zero_tangent data for the rule's forward pass as it results in `ArgumentError: zero_tangent not defined for Pointers`.
refer : 
Also fixes alias tuple test [case](https://github.com/chalk-lab/Mooncake.jl/blob/f0e3f9a2886782415fd8e2b13c1bc5008b5672d7/test/interface.jl#L151)  (tuples are stored by value, aliasing is not possible unless the elements are address based objects). Broadcasting `__exclude_unsupported_output` [here](https://github.com/chalk-lab/Mooncake.jl/blob/f0e3f9a2886782415fd8e2b13c1bc5008b5672d7/test/interface.jl#L176) gives a false pass on the tests.
refer:
=> fix supported primal checks in prepare_pullback_cache

Project.toml, ext/MooncakeLuxLibExt.jl, src/tangents.jl, test/integration_testing/lux/lux.jl
This PR fixes a Lux issue with dropout (https://github.com/chalk-lab/Mooncake.jl/issues/563) and adds a test for https://github.com/chalk-lab/Mooncake.jl/issues/622
Close https://github.com/chalk-lab/Mooncake.jl/issues/563 and add tests.
=> Add tangent_type for BigInt and rule for generate_dropout_mask

Project.toml, src/interpreter/bbcode.jl
It appears that, as of 1.11.6, basic block number `0` is now a predecessor of the first basic block in a `Core.Compiler.CFG`. Per the support policy, this PR drops support for `[1.11.1, 1.11.5]` in order to implement the fix.
edit: fixes #655
=> Update CFG Implementation

Project.toml, src/interface.jl, src/rrules/avoiding_non_differentiable_code.jl
I still need to add tests, but you can verify the usage by running code in issue #657 . @yebai @ChrisRackauckas suggestions on code are welcome.
I've added comments for the LLVM call error above the rule for the same (handle thread safe counters/reads) , the rules following it are specific to Base.CoreLogging's functions that use logstate etc. (specifically when logging selection does NOT affect numerical solver data, handles observation side effects like   @info etc), a few string manipulation Base functions (string operations).
```
julia> using Mooncake, OrdinaryDiffEq, StaticArrays
function lorenz!(du, u, p, t)
du[1] = 10.0(u[2] - u[1])
du[2] = u[1] * (28.0 - u[3]) - u[2]
du[3] = u[1] * u[2] - (8 / 3) * u[3]
end
const _saveat = SA[0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, …
```
=> fix for Base.CoreLogging usage in SciML solvers

Project.toml, src/rrules/misc.jl
Replaces a test which exposed non-determinism and NaNs to the correctness testing with something deterministic and NaN-free.
Specifically, consider the following:
```julia
julia> d = Dict("A" => 5, "B" => 4)
Dict{String, Int64} with 2 entries:
"B" => 4
"A" => 5
julia> d.vals
16-element Memory{Int64}:
0
4
5
0
0
0
0
0
0
0
0
0
0
0
0
0
julia> deepcopy(d).vals
16-element Memory{Int64}:
7306086968413740901
4
5
6878243912707629428
8391698316570687860
2985727426109923937
8891632269573496876
8243122710530505597
7017574069261122928
7592915475641558379
8387235708328572014
8101729628703978085
8457590201654274420
7814627425625142382
2964045190168474735
4906546432
```
That is, when `deepcopy`ing a `Dict`, Julia (correctly) considers it safe not to worry about any data which isn't meant to be exposed to …
=> Fix Flaky Test

Project.toml, src/tools_for_rules.jl
Fix https://github.com/chalk-lab/Mooncake.jl/issues/692. Alternative to https://github.com/chalk-lab/Mooncake.jl/pull/694
=> remove `const M`

test/integration_testing/bijectors/bijectors.jl
https://github.com/TuringLang/Bijectors.jl/pull/407 added missing rules so hopefully this test now passes.
=> Uncomment b_binv_test_case for PlanarLayer

docs/src/utilities/debug_mode.md, src/codual.jl, src/dual.jl, src/utils.jl
The PR cleans up docs on `_copy` and adds an overview of `_copy`'s current behaviour for different types
Replacing and closes https://github.com/chalk-lab/Mooncake.jl/pull/760
=> Revise documentation for internal `_copy` utility

Project.toml, src/rrules/lapack.jl, src/rrules/low_level_maths.jl, src/test_utils.jl, test/integration_testing/format/format.jl
I messed up the formatter in https://github.com/chalk-lab/Mooncake.jl/pull/770 -- it was pointing to the `test` folder only, rather than the entire package. As a result, a couple of recent PRs were merged without proper formatting.
This PR
1. fixes the formatter, making sure that it checks code in all directories in the package
2. fixes formatting of PRs that were merged while the formatter was not doing the right thing
3. bumps the patch version so that we can merge the updated code.
=> Fix Formatter

Project.toml, src/rrules/blas.jl
Tries to fix #622, and perhaps [#1392.](https://github.com/LuxDL/Lux.jl/issues/1392).
We check [blas.jl from LinearAlgebra](https://github.com/JuliaLang/LinearAlgebra.jl/blob/2c3fe9b7e0ca4e2c7bf506bd16ae5900f04a8023/src/blas.jl#LL1633C1-L1637C51) to check which of the operations and parameters need `AbstractVecOrMat`:
``` julia
$ rg -B8 AbstractVecOrMat LinearAlgebra/src/blas.jl | rg "function"
function gemv!(trans::AbstractChar, alpha::Union{($elty), Bool},
function gemmt!(uplo::AbstractChar, transA::AbstractChar, transB::AbstractChar,
function gemm!(transA::AbstractChar, transB::AbstractChar,
function syrk!(uplo::AbstractChar, trans::AbstractChar,
function syrk(uplo::AbstractChar, trans::AbstractChar, alpha::Number, A::AbstractVecOrMat)
function herk!(uplo::AbstractChar, …
```
=> Relax some blas dispatches to `AbstractVecOrMat`
